# --- defini o arquivo como .yml
---
name: Checks

# trigger que vai rodar no push
on: [push]

# job executado no push
jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1 # Permite uso de ações ou uses pre-criadas no repositorio de ações do GitHub
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py wait_for_db && migrate && python manage.py test" # comando de test, se retornar 0 ta tudo certo
      - name: Lint
        run: docker compose run --rm app sh -c "flake8" # comando de linting, se retornar nada, deu tudo certo